services:
  catalog-service-config-server:
    image: "ghcr.io/b1ackshadow/catalog-service-config-server"
    container_name: "catalog-service-config-server"
    ports:
      - 8888:8888
      - 8002:8002
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8002
      - CATALOG_SERVICE_CONFIG_URI=$CATALOG_SERVICE_CONFIG_URI
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
        interval: 5s
        timeout: 3s
        retries: 5

  catalog-service:
    depends_on: 
      polar-postgres: 
        condition: service_started
      catalog-service-config-server:
        condition: service_healthy
        
    image: "ghcr.io/b1ackshadow/catalog-service"
    container_name: "catalog-service"
    ports:
      - 9001:9001
      - 8001:8001
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres:5432/polardb_catalog
      - SPRING_PROFILES_ACTIVE=testdata
      - SPRING_CLOUD_CONFIG_URI=http://catalog-service-config-server:8888

  polar-postgres:
    image: "postgres"
    container_name: "polar-postgres"
    ports:
      - 5432:5432
    environment:
     - POSTGRES_USER=testuser 
     - POSTGRES_PASSWORD=testpass 
     - POSTGRES_INITDB_ARGS="-Amd5"
     - POSTGRES_DB=polardb_catalog

